#port ?? !!! ????? !!!

server:
  port: 9001

#jsp ??? ??
spring:
  mvc:
    view:
      prefix: /WEB-INF/mcar/
      suffix: .jsp

  #mysql setting
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bit701?serverTimezone=Asia/Seoul
    username: angel
    password: 1234

  #JPA setting
  #????? : create=?? ??? ?? ? ??, update: ??? ??? ??
  jpa:
    hibernate:
      ddl-auto: update
    #ddl ??? ?????? ??? ??? ??????? !! (??? true)
    generate-ddl: true
    #api ??? ???? sql?? ??? ??????..!
    show-sql: true
    #??? ??????? ?? !
    database: mysql
    #mysql ???? (???? ??? ?????? ?)
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
